name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 3 1 1 *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        path: LICENSE.md
        token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'cherry-pick:release/oss-v5,cherry-pick:release/oss-v21.10,lol-nope'